-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

-- | The abstract syntax of language numbers.

module AbsNumbers where

import Prelude (Integer)
import qualified Prelude as C (Eq, Ord, Show, Read)

data Exp
    = Plus Exp Exp
    | Minus Exp Exp
    | Times Exp Exp
    | Div Exp Exp
    | Neg Exp
    | Exp Exp Exp
    | Abs Exp
    | Mod Exp Exp
    | Num Integer
  deriving (C.Eq, C.Ord, C.Show, C.Read)

